site_name: Liu Theory Group wiki
site_description: Liu Theory Group wiki
theme: 
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  logo: asset/images/liushilab.jpg
  favicon: asset/images/liushilab.jpg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.action.view
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  hightlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
    - markdown
    - latex
    - c
    - cpp
    - fortran
    - makefile
    - cmake
    - shell
    - matlab
    - mathematica
    - julia
    - r
    - html
    - css
    - javascript
    - json
    - xml
    - ini
    - diff
    - dockerfile
    - nginx
    - sql
    - yaml
repo_url: https://github.com/sliutheorygroup/sliutheorygroup.github.io
repo_name: sliutheorygroup/sliutheorygroup.github.io
edit_uri: edit/main/docs/
nav:

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - tags